### PR TITLE
Fixes bug #109

### LINKED ISSUE #109: main rating (in circle) vanishes after switching and interacting with a non-shop tab.

### PR DESCRIPTION
**Pull request by CubeOfCheese**
Closes #109

### CODE REVIEW

File: Extension/content.js [hunk 1]
```diff
@@ -164,17 +166,29 @@ window.onload = function pageEval() {
...
     } else {
         chrome.runtime.sendMessage({ msgName: "PageEvaluated", shoppingPage: false }, function(response) {});
+        isShoppingPage = false;
     }
 };
 
+chrome.runtime.onMessage.addListener(
+    function(request, sender, sendResponse) {
+        if (request.msgName == "isShoppingPage?") {
+            console.log(isShoppingPage);
```
Comment (lindaicing) [inline Extension/content.js:186]: Did you want to keep this console.log?

File: Extension/content.js [hunk 2]
```diff
@@ -164,17 +166,29 @@ window.onload = function pageEval() {
     for (i = 0; i < shopWords.length; i++) {
         var inArray = shopWords[i].test(dom);
         if (inArray) { // if words are present, add values.
+            console.log(shopWords[i]);
```
Comment (lindaicing) [inline Extension/content.js:169]: Keep the console.log?

File: Extension/content.js (hunk 1 above)
Comment (CubeOfCheese) [reply Extension/content.js:186]: Nope!
